---
- hosts: localhost
 # become: true
  #become_user: root
  gather_facts: yes
  connection: local

  tasks:
  - name: "deploying test CFT to {{ Environment }} environment"
    cloudformation:
      #aws_access_key: "{{ aws_access_key }}"
      #aws_secret_key: "{{ aws_secret_key }}"
      stack_name: "{{ stack_name }}"
      state: "{{ state }}"
      #region: "{{ aws_region }}"
<<<<<<< HEAD
      disable_rollback: true
      #template: "test.json"
      template: "https://ogbayaml.s3.amazonaws.com/test.json"
=======
      disable_rollback: false
      template: "test.json"
>>>>>>> b4f4886b6a0516e2888b8df77f4306cb94c49466
      template_parameters:
        Environment: "{{ Environment }}"
    when: state == "present"

  - name: "deleting test CFT stack in {{ Environment }} environment"
    cloudformation:
      #aws_access_key: "{{ aws_access_key }}"
      #aws_secret_key: "{{ aws_secret_key }}"
      stack_name: "{{ stack_name }}"
      state: "{{ state }}"
      #region: "{{ aws_region }}"
<<<<<<< HEAD
      disable_rollback: true
      #template: "test.json"
      template: "https://ogbayaml.s3.amazonaws.com/test.json"
=======
      disable_rollback: false
      template: "test.json"
>>>>>>> b4f4886b6a0516e2888b8df77f4306cb94c49466
      template_parameters:
        Environment: "{{ Environment }}"
    when: state  == "absent"

